name: Post release topic on Discourse

on:
  release:
    tags:
      - 'jenkins-2\.\d{3}\.\d{1,3}(?:-rc)?$'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: Github Actions job result
          to: intellectualsites@googlegroups.com
          from: Jenkins Release Bot
          body: Build job of ${{github.repository}} completed successfully!
          ignore_cert: true
          convert_markdown: true
