name: Post release topic on Discourse

on:
  release:
    types: [published]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: roots/discourse-topic-github-release-action@main
        if: contains(github.event.release.tag_name, 'refs/tags/jenkins-2\.\d{3}\.\d{1,3}(?:-rc)?$')
        with:
          discourse-api-key: ${{ secrets.DISCOURSE_RELEASES_API_KEY }}
          discourse-base-url: https://community.jenkins.io/
          discourse-author-username: jenkins-release-bot
          discourse-category: 23
      - name: Send mail
        if: contains(github.event.release.tag_name, 'refs/tags/jenkins-2\.\d{3}\.\d{1,3}(?:-rc)?$')
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          subject: ${{ github.event.release.tag_name }} has been released
          to: intellectualsites@googlegroups.com
          from: Jenkins Release Bot
          html_body: ${{ github.event.release.body }}
          convert_markdown: true
