name: Post release topic on Discourse

on:
  release:
    types: [published]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Check if GITHUB_REF matches regex
        id: regex_check
        run: |
          if [[ ${{ github.event.release.tag_name }} = jenkins-2\.\d{3}\.\d{1,3}(?:-rc)?$ ]]; then
            echo "GITHUB_REF matches the regex syntax."
            echo "REF_MATCHES=true" >> $GITHUB_ENV
          else
            echo "GITHUB_REF does not match the regex syntax."
            echo "REF_MATCHES=false" >> $GITHUB_ENV
          fi
      - uses: roots/discourse-topic-github-release-action@main
        if: env.REF_MATCHES == 'true'
        with:
          discourse-api-key: ${{ secrets.DISCOURSE_RELEASES_API_KEY }}
          discourse-base-url: https://community.jenkins.io/
          discourse-author-username: jenkins-release-bot
          discourse-category: 23
      - name: Send mail
        if: env.REF_MATCHES == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          subject: ${{ github.event.release.tag_name }} has been released
          to: intellectualsites@googlegroups.com
          from: Jenkins Release Bot
          html_body: ${{ github.event.release.body }}
          convert_markdown: true
