name: Post release topic on Discourse

on:
  release:
    tags:
      - 'jenkins-2\.\d{3}\.\d{1,3}(?:-rc)?$'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          subject: ${{ github.event.release.tag_name }} has been released
          to: intellectualsites@googlegroups.com
          from: Jenkins Release Bot
          body: ${{ github.event.release.body }}
