name: Post release topic on Discourse

on:
  release:
    types:
      - prereleased
    tags:
      - 'jenkins-2\.\d+\.\d{1,2}$'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - uses: roots/discourse-topic-github-release-action@main
      with:
        discourse-api-key: ${{ secrets.DISCOURSE_RELEASES_API_KEY }}
        discourse-base-url: https://community.jenkins.io/
        discourse-author-username: NotMyFault
        discourse-category: 4
